# Generated by Django 5.2.7 on 2025-10-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('contenido_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('episodios', models.IntegerField()),
            ],
            options={
                'db_table': 'contenido',
            },
        ),
    ]
